import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'employees'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.increments('employee_id').notNullable()
      table.integer('employee_sync_id').notNullable()
      table.smallint('employee_status').notNullable()
      table.bigint('employee_code').notNullable()
      table.string('employee_first_name', 25).nullable()
      table.string('employee_last_name', 25).nullable()
      table.string('employee_nickname', 25).nullable()
      table.string('employee_passport', 30).nullable()
      table.string('employee_driver_license_automobile', 30).nullable()
      table.string('employee_driver_license_motorcycle', 30).nullable()
      table.string('employee_photo', 200).nullable()
      table.string('employee_self_password', 128).nullable()
      table.string('employee_device_password', 20).nullable()
      table.integer('employee_dev_privilege').nullable()
      table.string('employee_card_no', 20).nullable()
      table.string('employee_acc_group', 5).nullable()
      table.string('employee_acc_timezone', 20).nullable()
      table.string('employee_gender', 1).nullable()
      table.timestamp('employee_birthday').nullable()
      table.string('employee_address', 200).nullable()
      table.string('employee_postcode', 10).nullable()
      table.string('employee_office_tel', 20).nullable()
      table.string('employee_contact_tel', 20).nullable()
      table.string('employee_mobile', 30).nullable()
      table.string('employee_national_num', 50).nullable()
      table.string('employee_payroll_num', 50).nullable()
      table.string('employee_internal_num', 50).nullable()
      table.string('employee_national', 50).nullable()
      table.string('employee_religion', 20).nullable()
      table.string('employee_title', 20).nullable()
      table.string('employee_enroll_sn', 20).nullable()
      table.string('employee_ssn', 20).nullable()
      table.timestamp('employee_hire_date').nullable()
      table.integer('employee_verify_mode').nullable()
      table.string('employee_city', 20).nullable()
      table.boolean('employee_is_admin').notNullable()
      table.integer('employee_type').nullable()
      table.boolean('employee_enable_att').notNullable()
      table.boolean('employee_enable_payroll').notNullable()
      table.boolean('employee_enable_overtime').notNullable()
      table.boolean('employee_enable_holiday').notNullable()
      table.boolean('employee_deleted').notNullable()
      table.integer('employee_reserved').nullable()
      table.integer('employee_del_tag').nullable()
      table.smallint('employee_app_status').nullable()
      table.smallint('employee_app_role').nullable()
      table.string('employee_email', 50).nullable()
      table.timestamp('employee_last_login').nullable()
      table.boolean('employee_active').notNullable()
      table.smallint('employee_vacation_rule').nullable()
      table.integer('company_id').unsigned().notNullable()
      table.integer('department_id').unsigned().notNullable()
      table.integer('position_id').unsigned().notNullable()
      table.integer('department_sync_id').nullable()
      table.integer('position_sync_id').nullable()
      table.string('employee_create_user', 150).nullable()
      table.string('employee_change_user', 150).nullable()
      table.timestamp('employee_last_synchronization_at').nullable()
      table.foreign('department_id').references('departments.department_id')
      table.foreign('position_id').references('positions.position_id')

      table.timestamp('employee_created_at').notNullable()
      table.timestamp('employee_updated_at').nullable()
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
